name: Release

on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: [Run tests]
    types: [completed]

jobs:
  on-tests-success:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - name: Publish package distributions to PyPI
        run: pdm publish

  on-tests-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'tests failed, abort publishing'
      - run: exit 1
